# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\_Ruby\Test\Python\create_project_object\demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_msg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg.setGeometry(QtCore.QRect(60, 140, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.lbl_msg.setFont(font)
        self.lbl_msg.setStyleSheet("QLabel{\n"
"rgb(255, 0, 0);\n"
"font: 16pt \"Agency FB\";\n"
"}")
        self.lbl_msg.setText("")
        self.lbl_msg.setOpenExternalLinks(False)
        self.lbl_msg.setObjectName("lbl_msg")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 327, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ProjectName = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_ProjectName.setMaximumSize(QtCore.QSize(261, 111))
        self.lbl_ProjectName.setObjectName("lbl_ProjectName")
        self.horizontalLayout.addWidget(self.lbl_ProjectName)
        self.txt_ProjectName = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_ProjectName.setObjectName("txt_ProjectName")
        self.horizontalLayout.addWidget(self.txt_ProjectName)
        self.btn_Create = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_Create.setObjectName("btn_Create")
        self.horizontalLayout.addWidget(self.btn_Create)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 230, 301, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_ProjectName.setText(_translate("MainWindow", "<html><head/><body><p>專案名稱:</p></body></html>"))
        self.btn_Create.setText(_translate("MainWindow", "Create"))
